Shopping2/Models/CityViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Shopping2.Models
{
    public class CityViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Ciudad")]
        [MaxLength(50, ErrorMessage = "El campo {0} debe tener máximo {1} caractéres.")]
        [Required(ErrorMessage = "El campo {0} es obligatorio.")]
        public string Name { get; set; }

        public int StateId { get; set; }
    }
}

Shopping2/Models/StateViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Shopping2.Models
{
    public class StateViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Departamento/Estado")]
        [MaxLength(50, ErrorMessage = "El campo {0} debe tener máximo {1} caractéres.")]
        [Required(ErrorMessage = "El campo {0} es obligatorio.")]
        public string Name { get; set; }
         
        public int CountryId { get; set; }  
    }
}

Shopping2/Controllers/CountriesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shopping2.Data;
using Shopping2.Data.Entities;
using Shopping2.Helpers;
using Shopping2.Models;
using System.Data;
using System.Diagnostics.Metrics;
using Vereyon.Web;
using static Shopping2.Helpers.ModalHelper;

namespace Shopping2.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CountriesController : Controller
    {
        private readonly DataContext _context;
        private readonly IFlashMessage _flashMessage;

        public CountriesController(DataContext context,IFlashMessage flashMessage)
        {
            _context = context;
            _flashMessage=flashMessage;
        }

        // GET: Countries
        public async Task<IActionResult> Index()
        {
            
            return View(await _context.Countries
                .Include(c => c.States)
                .ThenInclude(s => s.Cities)
                .ToListAsync());
        }

        // GET: Countries/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var country = await _context.Countries
                .Include(c => c.States)
                .ThenInclude(s=> s.Cities)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (country == null)
            {
                return NotFound();
            }

            return View(country);
        }

        public async Task<IActionResult> DetailsState(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            State state = await _context.States
                .Include(c => c.Country)
                .Include(s => s.Cities)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (state == null)
            {
                return NotFound();
            }

            return View(state);
        }
       

        // GET: Countries/Create

        [NoDirectAccess]
        public async Task<IActionResult> AddState(int id)
        {
            

            Country country = await _context.Countries.FindAsync(id);
            if(country== null)
            {
                return NotFound();
            }
            StateViewModel model = new()
            {
                CountryId = country.Id,
            };
            return View(model);
        }

        // POST: Countries/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddState(StateViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    State state = new()
                    {
                        Cities= new List<City>(),
                        Country= await _context.Countries.FindAsync(model.CountryId),
                        Name=model.Name,    
                    };
                    _context.Add(state);
                    await _context.SaveChangesAsync();
                    Country country = await _context.Countries
               .Include(c => c.States)
               .ThenInclude(s => s.Cities)
               .FirstOrDefaultAsync(c => c.Id == model.CountryId);
                    _flashMessage.Info("Registro creado.");
                    return Json(new { isValid = true, html = ModalHelper.RenderRazorViewToString(this, "_ViewAllStates", country) });

                }
                catch (DbUpdateException dbUpdateException)
                {
                    if (dbUpdateException.InnerException.Message.Contains("duplicate"))
                    {
                        ModelState.AddModelError(string.Empty, "Ya existe un departamento con el mismo nombre en este país");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, dbUpdateException.InnerException.Message);
                    }
                }
                catch (Exception exception)
                {
                    ModelState.AddModelError(string.Empty, exception.Message);
                }

            }
            return Json(new { isValid = false, html = ModalHelper.RenderRazorViewToString(this, "AddState", model) });
        }

        [NoDirectAccess]
        public async Task<IActionResult> AddCity(int id)
        {
          

            State state = await _context.States.FindAsync(id);
            if (state == null)
            {
                return NotFound();
            }
            CityViewModel model = new()
            {
                StateId = state.Id,
            };
            return View(model);
        }

        // POST: Countries/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddCity(CityViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    City city = new()
                    {
                        
                        State = await _context.States.FindAsync(model.StateId),
                        Name = model.Name,
                    };
                    _context.Add(city);
                    await _context.SaveChangesAsync();
                    State state = await _context.States
                .Include(s => s.Cities)
                .FirstOrDefaultAsync(c => c.Id == model.StateId);
                    _flashMessage.Confirmation("Registro creado");
                    return Json(new { isValid = true, html = ModalHelper.RenderRazorViewToString(this, "_ViewAllCities", state) });

                }
                catch (DbUpdateException dbUpdateException)
                {
                    if (dbUpdateException.InnerException.Message.Contains("duplicate"))
                    {
                        ModelState.AddModelError(string.Empty, "Ya existe una ciudad con el mismo nombre en este departamento/estado.");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, dbUpdateException.InnerException.Message);
                    }
                }
                catch (Exception exception)
                {
                    ModelState.AddModelError(string.Empty, exception.Message);
                }

            }
            return Json(new { isValid = false, html = ModalHelper.RenderRazorViewToString(this, "CreateCity", model) });
        }
        // GET: Countries/Edit/5

        [NoDirectAccess]
        public async Task<IActionResult> EditState(int id)
        {
           

            State state = await _context.States
                .Include(x => x.Country)    
                .FirstOrDefaultAsync(s => s.Id==id);

            if (state == null)
            {
                return NotFound();
            }

            StateViewModel model = new()
            {
                CountryId = state.Country.Id,
                Id = state.Id,
                Name = state.Name,
            };
            return View(model);
        }

        // POST: Countries/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditState(int id, StateViewModel model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    State state = new()
                    { 
                        Id = model.Id,
                        Name= model.Name,
                    };
                    _context.Update(state);
                    Country country = await _context.Countries
                .Include(c => c.States)
                .ThenInclude(s => s.Cities)
                .FirstOrDefaultAsync(c => c.Id == model.CountryId);
                    await _context.SaveChangesAsync();
                    _flashMessage.Confirmation("Registro actualizado.");
                    return Json(new { isValid = true, html = ModalHelper.RenderRazorViewToString(this, "_ViewAllStates", country) });

                }
                catch (DbUpdateException dbUpdateException)
                {
                    if (dbUpdateException.InnerException.Message.Contains("duplicate"))
                    {
                        ModelState.AddModelError(string.Empty, "Ya existe un Departamento con el mismo nombre en este país.");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, dbUpdateException.InnerException.Message);
                    }
                }
                catch (Exception exception)
                {
                    ModelState.AddModelError(string.Empty, exception.Message);
                }

            }
            return Json(new { isValid = false, html = ModalHelper.RenderRazorViewToString(this, "EditState", model) });
        }

        [NoDirectAccess]
        public async Task<IActionResult> EditCity(int id)
        {
            

            City city = await _context.Cities
                .Include(c => c.State)
                .FirstOrDefaultAsync(c => c.Id == id);

            if (city == null)
            {
                return NotFound();
            }

Shopping2/Views/Countries/AddCity.cshtml
@model Shopping2.Models.CityViewModel

@{
    ViewData["Title"] = "Ciudad";
    Layout = null;
}

<flash dismissable="true" />

<div class="container smfont">
    <form asp-action="AddCity" autocomplete="off" asp-route-id="@Model.Id" onsubmit="return jQueryAjaxPost(this);">
        <div class="box-body">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="StateId" />
            <partial name="_City" />
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-sm btn-primary" data-bs-dismiss="modal"><i class="fa fa-ban"></i> Cancelar</button>
            <button type="submit" class="btn btn-sm btn-success"><i class="fa fa-save"></i> Guardar</button>
        </div>
    </form>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Shopping2/Views/Countries/AddOrEdit.cshtml
@model Shopping2.Data.Entities.Country

@{
    ViewData["Title"] = "País";
    Layout = null;
}

<flash dismissable="true" />

<div class="container smfont">
    <form asp-action="AddOrEdit" autocomplete="off" asp-route-id="@Model.Id" onsubmit="return jQueryAjaxPost(this);">
        <div class="box-body">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <span class="required">*</span>
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control smfont" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-sm btn-primary" data-bs-dismiss="modal"><i class="fa fa-ban"></i> Cancelar</button>
            <button type="submit" class="btn btn-sm btn-success"><i class="fa fa-save"></i> Guardar</button>
        </div>
    </form>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Shopping2/Views/Countries/DeleteState.cshtml
@model Shopping2.Data.Entities.State

@{
    ViewData["Title"] = "Delete";
}
<flash dismissable="true" />
<h1>Borrar</h1>

<h3>Esta seguro de querer borrar?</h3>
<partial name="_StateDetails" />
<div>
    <form asp-action="DeleteState">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Borrar" class="btn btn-outline-danger" />
        <a asp-action="Details" asp-route-id="@Model?.Country.Id" class="btn btn-outline-success">Regresar</a>
    </form>
</div>

Shopping2/Views/Countries/Details.cshtml
@model Shopping2.Data.Entities.Country

@{
    ViewData["Title"] = "Details";
}

<flash dismissable="true" />

<h1>Detalles</h1>

<div>
    <partial name="_CountryDetails" />
</div>

<div>
    <a asp-action="Index" class="btn btn-outline-success"><i class="fa-solid fa-arrow-rotate-left"></i> Regresar</a>
</div>
<hr />

<!-- Content Wrapper. Contains page content -->
<div class="container-fluid">
    <div class="card mt-2">
        <div class="card-header text-danger">
            <i class="fa fa-globe"></i>  <strong>Estados / Departamentos</strong>
        </div>
        <div class="card-body">
            <div id="view-all">
                @await Html.PartialAsync("_ViewAllStates", Model)
            </div>
        </div>
    </div>
</div>

<partial name="_AddOrEditDialog" />
<partial name="_DeleteDialog" />

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script src="~/js/showmodal.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#StatesTable').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
                },
                "aLengthMenu": [
                    [25, 50, 100, 200, -1],
                    [25, 50, 100, 200, "Todos"]
                ]
            });
        });
    </script>

    <script>
        sc_deleteDialog.openModal('deleteItem', true, 'btnYesDelete', '/Countries/DeleteState/', false);
    </script>
}

Shopping2/Views/Countries/DetailsState.cshtml
@model Shopping2.Data.Entities.State

@{
    ViewData["Title"] = "Details";
}

<flash dismissable="true" />

<h1>Detalles</h1>

<div>
    <partial name="_StateDetails" />
</div>

<div>
    <a asp-action="Details" asp-route-id="@Model?.Country.Id" class="btn btn-outline-success"><i class="fa-solid fa-arrow-rotate-left"></i> Regresar</a>
</div>
<hr />

<!-- Content Wrapper. Contains page content -->
<div class="container-fluid">
    <div class="card mt-2">
        <div class="card-header text-danger">
            <i class="fa fa-globe"></i>  <strong>Ciudades</strong>
        </div>
        <div class="card-body">
            <div id="view-all">
                @await Html.PartialAsync("_ViewAllCities", Model)
            </div>
        </div>
    </div>
</div>



<partial name="_AddOrEditDialog" />
<partial name="_DeleteDialog" />

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script src="~/js/showmodal.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#StatesTable').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
                },
                "aLengthMenu": [
                    [25, 50, 100, 200, -1],
                    [25, 50, 100, 200, "Todos"]
                ]
            });
        });
    </script>

    <script>
        sc_deleteDialog.openModal('deleteItem', true, 'btnYesDelete', '/Countries/DeleteCity/', false);
    </script>
}

Shopping2/Views/Countries/EditCity.cshtml
@model Shopping2.Models.CityViewModel

@{
    ViewData["Title"] = "Ciudad";
    Layout = null;
}

<flash dismissable="true" />

<div class="container smfont">
    <form asp-action="EditCity" autocomplete="off" asp-route-id="@Model.Id" onsubmit="return jQueryAjaxPost(this);">
        <div class="box-body">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="StateId" />
            <partial name="_City" />
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-sm btn-primary" data-bs-dismiss="modal"><i class="fa fa-ban"></i> Cancelar</button>
            <button type="submit" class="btn btn-sm btn-success"><i class="fa fa-save"></i> Guardar</button>
        </div>
    </form>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Shopping2/Views/Countries/Index.cshtml
@model IEnumerable<Shopping2.Data.Entities.Country>

@{
    ViewData["Title"] = "Index";
}

<flash dismissable="true" />

<!-- Content Wrapper. Contains page content -->
<div class="container-fluid">
    <div class="card mt-2">
        <div class="card-header text-danger">
            <i class="fa fa-globe"></i>  <strong>Países</strong>
        </div>
        <div class="card-body">
            <div id="view-all">
                @await Html.PartialAsync("_ViewAllCountries", Model)
            </div>
        </div>
    </div>
</div>

<partial name="_AddOrEditDialog" />
<partial name="_DeleteDialog" />

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script src="~/js/showmodal.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#CountriesTable').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
                },
                "aLengthMenu": [
                    [25, 50, 100, 200, -1],
                    [25, 50, 100, 200, "Todos"]
                ]
            });
        });
    </script>

    <script>
        sc_deleteDialog.openModal('deleteItem', true, 'btnYesDelete', '/Countries/Delete/', false);
    </script>
}

Shopping2/Views/Countries/_City.cshtml
@model Shopping2.Models.CityViewModel

<div class="form-group">
    <span class="required">*</span>
    <label asp-for="Name" class="control-label"></label>
    <input asp-for="Name" class="form-control" />
    <span asp-validation-for="Name" class="text-danger"></span>
</div>

Shopping2/Views/Countries/_CityDetails.cshtml
@model Shopping2.Data.Entities.City
<h4>Ciudad</h4>
<hr />
<dl class="row">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Name)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Name)
    </dd>
</dl>

Shopping2/Views/Countries/_CountryDetails.cshtml
@model Shopping2.Data.Entities.Country
<h4>País</h4>
<hr />
<dl class="row">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Name)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Name)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.StatesNumber)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.StatesNumber)
    </dd>
   
</dl>

Shopping2/Views/Countries/_State.cshtml
@model Shopping2.Models.StateViewModel

<div class="form-group">
    <span class="required">*</span>
    <label asp-for="Name" class="control-label"></label>
    <input asp-for="Name" class="form-control" />
    <span asp-validation-for="Name" class="text-danger"></span>
</div>

Shopping2/Views/Countries/_StateDetails.cshtml
@model Shopping2.Data.Entities.State
<h4>Departamentos/Estados</h4>
<hr />
<dl class="row">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Name)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Name)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.CitiesNumber)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.CitiesNumber)
    </dd>

</dl>

Shopping2/Views/Countries/_ViewAllCountries.cshtml
@model IEnumerable<Shopping2.Data.Entities.Country>

<flash dismissable="true" />

<table class="table table-striped table-responsive-md table-bordered smfont" id="CountriesTable">
    <colgroup>
        <col span="1" />
        <col span="1" />
        <col span="1" />
    </colgroup>
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StatesNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CitiesNumber)
            </th>
            <th>
                <a onclick="showInPopup('@Url.Action("AddOrEdit", "Countries", new { id = 0 }, Context.Request.Scheme)' , 'Nuevo País')" class="btn btn-sm btn-primary text-white"><i class="fa fa-plus-circle"></i> País</a>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-action="Details" asp-controller="Countries" asp-route-Id="@item.Id">@Html.DisplayFor(modelItem => item.Name)</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StatesNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CitiesNumber)
                </td>
                <td>
                    <a onclick="showInPopup('@Url.Action("AddOrEdit", "Countries", new { id = item.Id }, Context.Request.Scheme)' , 'Actualizar País')" class="btn btn-sm btn-warning"><i class="fa fa-pencil-alt"></i> </a>
                    <button data-id="@item.Id" class="btn btn-sm btn-danger deleteItem" data-bs-toggle="modal" data-bs-target="#deleteDialog"><i class="fa fa-trash"></i></button>
                </td>
            </tr>
        }
    </tbody>
</table>

Shopping2/Views/Countries/_ViewAllStates.cshtml
@model Shopping2.Data.Entities.Country

<flash dismissable="true" />

<table class="table table-striped table-responsive-md table-bordered smfont" id="StatesTable">
    <colgroup>
        <col span="1" />
        <col span="1" />
    </colgroup>
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.States.FirstOrDefault().Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.States.FirstOrDefault().CitiesNumber)
            </th>
            <th>
                <a onclick="showInPopup('@Url.Action("AddState", "Countries", new { id = Model?.Id }, Context.Request.Scheme)' , 'Nuevo Estado / Departamento')" class="btn btn-sm btn-primary text-white"><i class="fa fa-plus-circle"></i> Estado / Departamento</a>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model?.States)
        {
            <tr>
                <td>
                    <a asp-action="DetailsState" asp-controller="Countries" asp-route-Id="@item.Id">@Html.DisplayFor(modelItem => item.Name)</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CitiesNumber)
                </td>
                <td>
                    <a onclick="showInPopup('@Url.Action("EditState", "Countries", new { id = item.Id }, Context.Request.Scheme)' , 'Actualizar Estado / Departamento')" class="btn btn-sm btn-warning"><i class="fa fa-pencil-alt"></i> </a>
                    <button data-id="@item.Id" class="btn btn-sm btn-danger deleteItem" data-bs-toggle="modal" data-bs-target="#deleteDialog"><i class="fa fa-trash"></i></button>
                </td>
            </tr>
        }
    </tbody>
</table>